### ISSUE TITLE
All files are written to root of target directory

### ISSUE THREAD

**Issue by effervescentia** [start-runner/write#19]
`v2.0.1` introduced a bug that forces all files passed to `start-write` to be written to the output folder specified, no matter the depth of nesting.

**Comment by deepsweet** [comment]
could you please show me your task?

**Comment by effervescentia** [comment]
So my `build` preset is essentially the exact same as yours, however after the `2.0.1` update the filetree is flattened into the output directory

https://github.com/effervescentia/re-start/blob/master/lib/commands/build.js

Before:
<img width="281" alt="screen shot 2017-02-16 at 11 18 24 am" src="https://cloud.githubusercontent.com/assets/3784470/23029810/b90ce07a-f439-11e6-95cc-8c33e7139cd6.png">

After:
<img width="264" alt="screen shot 2017-02-16 at 11 18 49 am" src="https://cloud.githubusercontent.com/assets/3784470/23029824/c0e77ba2-f439-11e6-9015-2926eb2a99c3.png">

**Comment by deepsweet** [comment]
ok, I'm able to reproduce, working on the fix. was pretty sure it's just a patch.

**Comment by effervescentia** [comment]
I also added [this package (start-split)](https://github.com/effervescentia/start-split) to deal with writing to multiple output directories (for preserving relative file structure for typescript builds). Is there some way you could enable this through `start-write`? It was mostly to get around the fact that `write` removes the root directory (`src/` for example) which I agree with, but maybe it could be turned off with an option? In that case `start-split` can be relegated to just be used for concurrent file writing

**Comment by deepsweet** [comment]
#20
